name: Build distributions

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run dist:mac
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: release/*

  windows:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run dist:win
      - uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: release/*
